#!/bin/bash

# Install docker on next reboot
#which docker > /dev/null
#if [ $? -ne 0 ]; then
#	echo "Installing Docker..."
#	/boot/dietpi/dietpi-software reinstall 162
#fi

# Start AS4H at Boot
su -s /bin/bash loxberry -c "REPLACELBPBINDIR/as_watchdog.pl --action=check --verbose=1"
su -s /bin/bash loxberry -c "REPLACELBPBINDIR/gw_watchdog.pl --action=check --verbose=1"
